/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import java.util.Objects;
import java.util.Arrays;
import com.dalet.mediator.metadataanalysis.model.ClassifierCategory;
import com.dalet.mediator.metadataanalysis.model.Entity;
import com.dalet.mediator.metadataanalysis.model.Topic;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AnalyzedTextResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-04T14:41:39.145+08:00[GMT+08:00]")
public class AnalyzedTextResponse {
  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language;

  public static final String SERIALIZED_NAME_LANGUAGE_IS_RELIABLE = "languageIsReliable";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_IS_RELIABLE)
  private Boolean languageIsReliable;

  public static final String SERIALIZED_NAME_ENTITIES = "entities";
  @SerializedName(SERIALIZED_NAME_ENTITIES)
  private List<Entity> entities = null;

  public static final String SERIALIZED_NAME_TOPICS = "topics";
  @SerializedName(SERIALIZED_NAME_TOPICS)
  private List<Topic> topics = null;

  public static final String SERIALIZED_NAME_CATEGORIES = "categories";
  @SerializedName(SERIALIZED_NAME_CATEGORIES)
  private List<ClassifierCategory> categories = null;


  public AnalyzedTextResponse language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public AnalyzedTextResponse languageIsReliable(Boolean languageIsReliable) {
    
    this.languageIsReliable = languageIsReliable;
    return this;
  }

   /**
   * Get languageIsReliable
   * @return languageIsReliable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getLanguageIsReliable() {
    return languageIsReliable;
  }


  public void setLanguageIsReliable(Boolean languageIsReliable) {
    this.languageIsReliable = languageIsReliable;
  }


  public AnalyzedTextResponse entities(List<Entity> entities) {
    
    this.entities = entities;
    return this;
  }

  public AnalyzedTextResponse addEntitiesItem(Entity entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<Entity>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Entity> getEntities() {
    return entities;
  }


  public void setEntities(List<Entity> entities) {
    this.entities = entities;
  }


  public AnalyzedTextResponse topics(List<Topic> topics) {
    
    this.topics = topics;
    return this;
  }

  public AnalyzedTextResponse addTopicsItem(Topic topicsItem) {
    if (this.topics == null) {
      this.topics = new ArrayList<Topic>();
    }
    this.topics.add(topicsItem);
    return this;
  }

   /**
   * List of topics detected in the text. each detected topic refers to wikiLink and wikidataId or None if no wikipedia reference is found.
   * @return topics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of topics detected in the text. each detected topic refers to wikiLink and wikidataId or None if no wikipedia reference is found.")

  public List<Topic> getTopics() {
    return topics;
  }


  public void setTopics(List<Topic> topics) {
    this.topics = topics;
  }


  public AnalyzedTextResponse categories(List<ClassifierCategory> categories) {
    
    this.categories = categories;
    return this;
  }

  public AnalyzedTextResponse addCategoriesItem(ClassifierCategory categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<ClassifierCategory>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * List of categories associated to the text. IPTC news codes refer to - http://cv.iptc.org/newscodes/subjectcode IPTC media topics refer to - http://cv.iptc.org/newscodes/mediatopic IAB taxonomy refer to - https://www.iab.com/guidelines/taxonomy
   * @return categories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of categories associated to the text. IPTC news codes refer to - http://cv.iptc.org/newscodes/subjectcode IPTC media topics refer to - http://cv.iptc.org/newscodes/mediatopic IAB taxonomy refer to - https://www.iab.com/guidelines/taxonomy")

  public List<ClassifierCategory> getCategories() {
    return categories;
  }


  public void setCategories(List<ClassifierCategory> categories) {
    this.categories = categories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalyzedTextResponse analyzedTextResponse = (AnalyzedTextResponse) o;
    return Objects.equals(this.language, analyzedTextResponse.language) &&
        Objects.equals(this.languageIsReliable, analyzedTextResponse.languageIsReliable) &&
        Objects.equals(this.entities, analyzedTextResponse.entities) &&
        Objects.equals(this.topics, analyzedTextResponse.topics) &&
        Objects.equals(this.categories, analyzedTextResponse.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, languageIsReliable, entities, topics, categories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalyzedTextResponse {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    languageIsReliable: ").append(toIndentedString(languageIsReliable)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    topics: ").append(toIndentedString(topics)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

