/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import java.util.Objects;
import java.util.Arrays;
import com.dalet.mediator.metadataanalysis.model.Mention;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-03T19:24:04.607+08:00[GMT+08:00]")
public class Entity {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    UNKNOWN("UNKNOWN"),
    
    PERSON("PERSON"),
    
    LOCATION("LOCATION"),
    
    ORGANIZATION("ORGANIZATION"),
    
    EVENT("EVENT"),
    
    WORKOFART("WORKOFART"),
    
    CONSUMERGOOD("CONSUMERGOOD"),
    
    OTHER("OTHER"),
    
    PHONENUMBER("PHONENUMBER"),
    
    ADDRESS("ADDRESS"),
    
    DATE("DATE"),
    
    NUMBER("NUMBER"),
    
    PRICE("PRICE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_MID = "mid";
  @SerializedName(SERIALIZED_NAME_MID)
  private String mid;

  public static final String SERIALIZED_NAME_WIKIPEDIA_URL = "wikipediaUrl";
  @SerializedName(SERIALIZED_NAME_WIKIPEDIA_URL)
  private String wikipediaUrl;

  public static final String SERIALIZED_NAME_SALIENCE = "salience";
  @SerializedName(SERIALIZED_NAME_SALIENCE)
  private java.lang.Double salience;

  public static final String SERIALIZED_NAME_MENTIONS = "mentions";
  @SerializedName(SERIALIZED_NAME_MENTIONS)
  private List<Mention> mentions = null;


  public Entity name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Entity type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public Entity mid(String mid) {
    
    this.mid = mid;
    return this;
  }

   /**
   * Google knowledge graph id when detected.
   * @return mid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Google knowledge graph id when detected.")

  public String getMid() {
    return mid;
  }


  public void setMid(String mid) {
    this.mid = mid;
  }


  public Entity wikipediaUrl(String wikipediaUrl) {
    
    this.wikipediaUrl = wikipediaUrl;
    return this;
  }

   /**
   * Get wikipediaUrl
   * @return wikipediaUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getWikipediaUrl() {
    return wikipediaUrl;
  }


  public void setWikipediaUrl(String wikipediaUrl) {
    this.wikipediaUrl = wikipediaUrl;
  }


  public Entity salience(java.lang.Double salience) {
    
    this.salience = salience;
    return this;
  }

   /**
   * The salience score associated with the entity in the [0, 1.0] range. The salience score for an entity provides information about the importance or centrality of that entity to the entire document text. Scores closer to 0 are less salient, while scores closer to 1.0 are highly salient.
   * @return salience
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The salience score associated with the entity in the [0, 1.0] range. The salience score for an entity provides information about the importance or centrality of that entity to the entire document text. Scores closer to 0 are less salient, while scores closer to 1.0 are highly salient.")

  public java.lang.Double getSalience() {
    return salience;
  }


  public void setSalience(java.lang.Double salience) {
    this.salience = salience;
  }


  public Entity mentions(List<Mention> mentions) {
    
    this.mentions = mentions;
    return this;
  }

  public Entity addMentionsItem(Mention mentionsItem) {
    if (this.mentions == null) {
      this.mentions = new ArrayList<Mention>();
    }
    this.mentions.add(mentionsItem);
    return this;
  }

   /**
   * Get mentions
   * @return mentions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Mention> getMentions() {
    return mentions;
  }


  public void setMentions(List<Mention> mentions) {
    this.mentions = mentions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity entity = (Entity) o;
    return Objects.equals(this.name, entity.name) &&
        Objects.equals(this.type, entity.type) &&
        Objects.equals(this.mid, entity.mid) &&
        Objects.equals(this.wikipediaUrl, entity.wikipediaUrl) &&
        Objects.equals(this.salience, entity.salience) &&
        Objects.equals(this.mentions, entity.mentions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, mid, wikipediaUrl, salience, mentions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entity {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
    sb.append("    wikipediaUrl: ").append(toIndentedString(wikipediaUrl)).append("\n");
    sb.append("    salience: ").append(toIndentedString(salience)).append("\n");
    sb.append("    mentions: ").append(toIndentedString(mentions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

