/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Topic
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-03T19:24:04.607+08:00[GMT+08:00]")
public class Topic {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_WIKI_LINK = "wikiLink";
  @SerializedName(SERIALIZED_NAME_WIKI_LINK)
  private String wikiLink;

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  private java.lang.Double score;

  public static final String SERIALIZED_NAME_WIKIDATA_ID = "wikidataId";
  @SerializedName(SERIALIZED_NAME_WIKIDATA_ID)
  private String wikidataId;


  public Topic id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Topic label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public Topic wikiLink(String wikiLink) {
    
    this.wikiLink = wikiLink;
    return this;
  }

   /**
   * Link to Wikipedia for this topic, or None if this topic couldn&#39;t be linked to a Wikipedia page.
   * @return wikiLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Link to Wikipedia for this topic, or None if this topic couldn't be linked to a Wikipedia page.")

  public String getWikiLink() {
    return wikiLink;
  }


  public void setWikiLink(String wikiLink) {
    this.wikiLink = wikiLink;
  }


  public Topic score(java.lang.Double score) {
    
    this.score = score;
    return this;
  }

   /**
   * The relevance of this topic to the processed document. This score ranges from 0 to 1, with 1 representing the highest relevance of the topic to the processed document.
   * @return score
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The relevance of this topic to the processed document. This score ranges from 0 to 1, with 1 representing the highest relevance of the topic to the processed document.")

  public java.lang.Double getScore() {
    return score;
  }


  public void setScore(java.lang.Double score) {
    this.score = score;
  }


  public Topic wikidataId(String wikidataId) {
    
    this.wikidataId = wikidataId;
    return this;
  }

   /**
   * The disambiguated Wikidata QID for this topic, or None if either this topic could not be disambiguated, or a Wikidata link doesn’t exist.
   * @return wikidataId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The disambiguated Wikidata QID for this topic, or None if either this topic could not be disambiguated, or a Wikidata link doesn’t exist.")

  public String getWikidataId() {
    return wikidataId;
  }


  public void setWikidataId(String wikidataId) {
    this.wikidataId = wikidataId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Topic topic = (Topic) o;
    return Objects.equals(this.id, topic.id) &&
        Objects.equals(this.label, topic.label) &&
        Objects.equals(this.wikiLink, topic.wikiLink) &&
        Objects.equals(this.score, topic.score) &&
        Objects.equals(this.wikidataId, topic.wikidataId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, wikiLink, score, wikidataId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Topic {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    wikiLink: ").append(toIndentedString(wikiLink)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    wikidataId: ").append(toIndentedString(wikidataId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

