/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Contains information about the request.
 */
@ApiModel(description = "Contains information about the request.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-03T19:24:04.607+08:00[GMT+08:00]")
public class TranslateTextRequest {
  public static final String SERIALIZED_NAME_RESOURCE = "resource";
  @SerializedName(SERIALIZED_NAME_RESOURCE)
  private Map<String, Object> resource = null;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_SOURCE_LANGUAGE = "sourceLanguage";
  @SerializedName(SERIALIZED_NAME_SOURCE_LANGUAGE)
  private String sourceLanguage;

  public static final String SERIALIZED_NAME_TARGET_LANGUAGE = "targetLanguage";
  @SerializedName(SERIALIZED_NAME_TARGET_LANGUAGE)
  private String targetLanguage;


  public TranslateTextRequest resource(Map<String, Object> resource) {
    
    this.resource = resource;
    return this;
  }

  public TranslateTextRequest putResourceItem(String key, Object resourceItem) {
    if (this.resource == null) {
      this.resource = new HashMap<String, Object>();
    }
    this.resource.put(key, resourceItem);
    return this;
  }

   /**
   * Use this field to associate metadata for the translate request.
   * @return resource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Use this field to associate metadata for the translate request.")

  public Map<String, Object> getResource() {
    return resource;
  }


  public void setResource(Map<String, Object> resource) {
    this.resource = resource;
  }


  public TranslateTextRequest text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(required = true, value = "")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public TranslateTextRequest sourceLanguage(String sourceLanguage) {
    
    this.sourceLanguage = sourceLanguage;
    return this;
  }

   /**
   * Get sourceLanguage
   * @return sourceLanguage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSourceLanguage() {
    return sourceLanguage;
  }


  public void setSourceLanguage(String sourceLanguage) {
    this.sourceLanguage = sourceLanguage;
  }


  public TranslateTextRequest targetLanguage(String targetLanguage) {
    
    this.targetLanguage = targetLanguage;
    return this;
  }

   /**
   * Get targetLanguage
   * @return targetLanguage
  **/
  @ApiModelProperty(required = true, value = "")

  public String getTargetLanguage() {
    return targetLanguage;
  }


  public void setTargetLanguage(String targetLanguage) {
    this.targetLanguage = targetLanguage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslateTextRequest translateTextRequest = (TranslateTextRequest) o;
    return Objects.equals(this.resource, translateTextRequest.resource) &&
        Objects.equals(this.text, translateTextRequest.text) &&
        Objects.equals(this.sourceLanguage, translateTextRequest.sourceLanguage) &&
        Objects.equals(this.targetLanguage, translateTextRequest.targetLanguage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, text, sourceLanguage, targetLanguage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslateTextRequest {\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    sourceLanguage: ").append(toIndentedString(sourceLanguage)).append("\n");
    sb.append("    targetLanguage: ").append(toIndentedString(targetLanguage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

