/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import java.util.Objects;
import java.util.Arrays;
import com.dalet.mediator.metadataanalysis.model.Locator;
import com.dalet.mediator.metadataanalysis.model.TranslateCaptionsResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TranslateCaptionsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-04T14:41:39.145+08:00[GMT+08:00]")
public class TranslateCaptionsRequest {
  public static final String SERIALIZED_NAME_SOURCE_SUBTITLE = "sourceSubtitle";
  @SerializedName(SERIALIZED_NAME_SOURCE_SUBTITLE)
  private Locator sourceSubtitle;

  public static final String SERIALIZED_NAME_OUTPUT_LOCATION = "outputLocation";
  @SerializedName(SERIALIZED_NAME_OUTPUT_LOCATION)
  private TranslateCaptionsResponse outputLocation;

  public static final String SERIALIZED_NAME_TARGET_LANGUAGE = "targetLanguage";
  @SerializedName(SERIALIZED_NAME_TARGET_LANGUAGE)
  private String targetLanguage;

  public static final String SERIALIZED_NAME_SKELETON_MODE = "skeletonMode";
  @SerializedName(SERIALIZED_NAME_SKELETON_MODE)
  private Boolean skeletonMode = true;

  public static final String SERIALIZED_NAME_SOURCE_LANGUAGE = "sourceLanguage";
  @SerializedName(SERIALIZED_NAME_SOURCE_LANGUAGE)
  private String sourceLanguage;


  public TranslateCaptionsRequest sourceSubtitle(Locator sourceSubtitle) {
    
    this.sourceSubtitle = sourceSubtitle;
    return this;
  }

   /**
   * Get sourceSubtitle
   * @return sourceSubtitle
  **/
  @ApiModelProperty(required = true, value = "")

  public Locator getSourceSubtitle() {
    return sourceSubtitle;
  }


  public void setSourceSubtitle(Locator sourceSubtitle) {
    this.sourceSubtitle = sourceSubtitle;
  }


  public TranslateCaptionsRequest outputLocation(TranslateCaptionsResponse outputLocation) {
    
    this.outputLocation = outputLocation;
    return this;
  }

   /**
   * Get outputLocation
   * @return outputLocation
  **/
  @ApiModelProperty(required = true, value = "")

  public TranslateCaptionsResponse getOutputLocation() {
    return outputLocation;
  }


  public void setOutputLocation(TranslateCaptionsResponse outputLocation) {
    this.outputLocation = outputLocation;
  }


  public TranslateCaptionsRequest targetLanguage(String targetLanguage) {
    
    this.targetLanguage = targetLanguage;
    return this;
  }

   /**
   * Get targetLanguage
   * @return targetLanguage
  **/
  @ApiModelProperty(required = true, value = "")

  public String getTargetLanguage() {
    return targetLanguage;
  }


  public void setTargetLanguage(String targetLanguage) {
    this.targetLanguage = targetLanguage;
  }


  public TranslateCaptionsRequest skeletonMode(Boolean skeletonMode) {
    
    this.skeletonMode = skeletonMode;
    return this;
  }

   /**
   * Get skeletonMode
   * @return skeletonMode
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSkeletonMode() {
    return skeletonMode;
  }


  public void setSkeletonMode(Boolean skeletonMode) {
    this.skeletonMode = skeletonMode;
  }


  public TranslateCaptionsRequest sourceLanguage(String sourceLanguage) {
    
    this.sourceLanguage = sourceLanguage;
    return this;
  }

   /**
   * Get sourceLanguage
   * @return sourceLanguage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSourceLanguage() {
    return sourceLanguage;
  }


  public void setSourceLanguage(String sourceLanguage) {
    this.sourceLanguage = sourceLanguage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslateCaptionsRequest translateCaptionsRequest = (TranslateCaptionsRequest) o;
    return Objects.equals(this.sourceSubtitle, translateCaptionsRequest.sourceSubtitle) &&
        Objects.equals(this.outputLocation, translateCaptionsRequest.outputLocation) &&
        Objects.equals(this.targetLanguage, translateCaptionsRequest.targetLanguage) &&
        Objects.equals(this.skeletonMode, translateCaptionsRequest.skeletonMode) &&
        Objects.equals(this.sourceLanguage, translateCaptionsRequest.sourceLanguage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceSubtitle, outputLocation, targetLanguage, skeletonMode, sourceLanguage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslateCaptionsRequest {\n");
    sb.append("    sourceSubtitle: ").append(toIndentedString(sourceSubtitle)).append("\n");
    sb.append("    outputLocation: ").append(toIndentedString(outputLocation)).append("\n");
    sb.append("    targetLanguage: ").append(toIndentedString(targetLanguage)).append("\n");
    sb.append("    skeletonMode: ").append(toIndentedString(skeletonMode)).append("\n");
    sb.append("    sourceLanguage: ").append(toIndentedString(sourceLanguage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

