/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AnalyzeRequest
 */
public class AnalyzeRequestTest {
    private final AnalyzeRequest model = new AnalyzeRequest();

    /**
     * Model tests for AnalyzeRequest
     */
    @Test
    public void testAnalyzeRequest() {
        // TODO: test AnalyzeRequest
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'extractors'
     */
    @Test
    public void extractorsTest() {
        // TODO: test extractors
    }

    /**
     * Test the property 'extractorsScoreThreshold'
     */
    @Test
    public void extractorsScoreThresholdTest() {
        // TODO: test extractorsScoreThreshold
    }

    /**
     * Test the property 'classifiers'
     */
    @Test
    public void classifiersTest() {
        // TODO: test classifiers
    }

    /**
     * Test the property 'classifierScoreThreshold'
     */
    @Test
    public void classifierScoreThresholdTest() {
        // TODO: test classifierScoreThreshold
    }

}
