/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KnowledgeGraphDetailedDescription
 */
public class KnowledgeGraphDetailedDescriptionTest {
    private final KnowledgeGraphDetailedDescription model = new KnowledgeGraphDetailedDescription();

    /**
     * Model tests for KnowledgeGraphDetailedDescription
     */
    @Test
    public void testKnowledgeGraphDetailedDescription() {
        // TODO: test KnowledgeGraphDetailedDescription
    }

    /**
     * Test the property 'articleBody'
     */
    @Test
    public void articleBodyTest() {
        // TODO: test articleBody
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

}
