/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Locator
 */
public class LocatorTest {
    private final Locator model = new Locator();

    /**
     * Model tests for Locator
     */
    @Test
    public void testLocator() {
        // TODO: test Locator
    }

    /**
     * Test the property 'awsS3Bucket'
     */
    @Test
    public void awsS3BucketTest() {
        // TODO: test awsS3Bucket
    }

    /**
     * Test the property 'awsS3Key'
     */
    @Test
    public void awsS3KeyTest() {
        // TODO: test awsS3Key
    }

    /**
     * Test the property 'httpEndpoint'
     */
    @Test
    public void httpEndpointTest() {
        // TODO: test httpEndpoint
    }

}
