/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.dalet.mediator.metadataanalysis.model.Locator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SegmentTextResponse
 */
public class SegmentTextResponseTest {
    private final SegmentTextResponse model = new SegmentTextResponse();

    /**
     * Model tests for SegmentTextResponse
     */
    @Test
    public void testSegmentTextResponse() {
        // TODO: test SegmentTextResponse
    }

    /**
     * Test the property 'dpttFile'
     */
    @Test
    public void dpttFileTest() {
        // TODO: test dpttFile
    }

    /**
     * Test the property 'draftjsFile'
     */
    @Test
    public void draftjsFileTest() {
        // TODO: test draftjsFile
    }

}
