/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.dalet.mediator.metadataanalysis.model.Locator;
import com.dalet.mediator.metadataanalysis.model.SegmentTextResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SegmentTextRequest
 */
public class SegmentTextRequestTest {
    private final SegmentTextRequest model = new SegmentTextRequest();

    /**
     * Model tests for SegmentTextRequest
     */
    @Test
    public void testSegmentTextRequest() {
        // TODO: test SegmentTextRequest
    }

    /**
     * Test the property 'inputFile'
     */
    @Test
    public void inputFileTest() {
        // TODO: test inputFile
    }

    /**
     * Test the property 'outputLocation'
     */
    @Test
    public void outputLocationTest() {
        // TODO: test outputLocation
    }

    /**
     * Test the property 'lines'
     */
    @Test
    public void linesTest() {
        // TODO: test lines
    }

    /**
     * Test the property 'characters'
     */
    @Test
    public void charactersTest() {
        // TODO: test characters
    }

}
