/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.dalet.mediator.metadataanalysis.model.Locator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TranslateCaptionsResponse
 */
public class TranslateCaptionsResponseTest {
    private final TranslateCaptionsResponse model = new TranslateCaptionsResponse();

    /**
     * Model tests for TranslateCaptionsResponse
     */
    @Test
    public void testTranslateCaptionsResponse() {
        // TODO: test TranslateCaptionsResponse
    }

    /**
     * Test the property 'ttmlFile'
     */
    @Test
    public void ttmlFileTest() {
        // TODO: test ttmlFile
    }

    /**
     * Test the property 'textFile'
     */
    @Test
    public void textFileTest() {
        // TODO: test textFile
    }

}
