/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TranslateTextResponse
 */
public class TranslateTextResponseTest {
    private final TranslateTextResponse model = new TranslateTextResponse();

    /**
     * Model tests for TranslateTextResponse
     */
    @Test
    public void testTranslateTextResponse() {
        // TODO: test TranslateTextResponse
    }

    /**
     * Test the property 'detectedSourceLanguage'
     */
    @Test
    public void detectedSourceLanguageTest() {
        // TODO: test detectedSourceLanguage
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

}
