/*
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dalet.mediator.metadataanalysis.model;

import com.dalet.mediator.metadataanalysis.model.Locator;
import com.dalet.mediator.metadataanalysis.model.TranslateCaptionsResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TranslateCaptionsRequest
 */
public class TranslateCaptionsRequestTest {
    private final TranslateCaptionsRequest model = new TranslateCaptionsRequest();

    /**
     * Model tests for TranslateCaptionsRequest
     */
    @Test
    public void testTranslateCaptionsRequest() {
        // TODO: test TranslateCaptionsRequest
    }

    /**
     * Test the property 'sourceSubtitle'
     */
    @Test
    public void sourceSubtitleTest() {
        // TODO: test sourceSubtitle
    }

    /**
     * Test the property 'outputLocation'
     */
    @Test
    public void outputLocationTest() {
        // TODO: test outputLocation
    }

    /**
     * Test the property 'targetLanguage'
     */
    @Test
    public void targetLanguageTest() {
        // TODO: test targetLanguage
    }

    /**
     * Test the property 'skeletonMode'
     */
    @Test
    public void skeletonModeTest() {
        // TODO: test skeletonMode
    }

    /**
     * Test the property 'sourceLanguage'
     */
    @Test
    public void sourceLanguageTest() {
        // TODO: test sourceLanguage
    }

}
